apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
#  namespace: kube-logging
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30112
  selector:
    app: kibana
